### ISSUE TITLE
3.0.2 throws TypeError: definitions.trim is not a function

### ISSUE THREAD

**Issue by gihrig** [prisma/graphql-middleware#198]
In prisma/photon TS example [graphql-auth](https://github.com/prisma/photonjs/blob/60fb8df1bba0f67bca6f94a9662227d3fc7d0732/examples/typescript/graphql-auth/src/index.ts#L41) a comment references non-working graphql-shield in issue [#361](https://github.com/maticzav/graphql-shield/issues/361)

The problem appears when graphql-middleware 3.0.2 is installed as a dependency of graphql-yoga.

Resolving graphql-middleware to 3.0.1 eliminates the error and graphql-shield works as expected.
**_Only works with `yarn`, `npm install` does not process `resolutions`_**

```json
"resolutions": {
  "graphql-middleware": "3.0.1"
}
```

```shell
$ ts-node-dev --no-notify --respawn --transpileOnly ./src
Using ts-node version 8.3.0, typescript version 3.5.3
TypeError: definitions.trim is not a function
    at parseFragmentToInlineFragment (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/fragments.ts:85:21)
    at /Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/fragments.ts:41:24
    at Array.map (<anonymous>)
    at Object.extractFragmentReplacements (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/fragments.ts:40:6)
    at addMiddlewareToSchema (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/middleware.ts:40:32)
    at normalisedMiddlewares.reduceRight.schema (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/middleware.ts:86:13)
    at Array.reduceRight (<anonymous>)
    at applyMiddlewareWithOptions (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/middleware.ts:78:77)
    at applyMiddleware (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-middleware/src/middleware.ts:129:36)
    at new GraphQLServer (/Users/glen/Documents/JavaScript/Research/hello-photon-graphql-auth/node_modules/graphql-yoga/src/index.ts:137:13)
[ERROR] 18:09:25 TypeError: definitions.trim is not a function
```

**Comment by gihrig** [comment]
@maticzav please merge [6e1b5c7](https://github.com/prisma/graphql-middleware/commit/6e1b5c7c22309c60048c887ad2ed6634805923a9) into master so the fix can propagate to graphql-yoga.

Then this issue can be closed as well as graphql-shield [#361](https://github.com/maticzav/graphql-shield/issues/361)

**Comment by gihrig** [comment]
@maticzav I have confirmed that 4.0.0 resolves the issue.

Thank you! :-)

**Comment by terion-name** [comment]
getting this on 4.0.1
